name: importer
channels:
  - anacond # lxml
  - conda-forge # pendulum, pip, python, httpx, fire, python-dotenv
dependencies:
  - python=3.8
  - pendulum
  - httpx
  - fire
  - lxml
  - python-dotenv
  - pip
  - pip:
      - git+https://github.com/QratorLabs/fastenum.git
      - xml-dataclasses
