name: importer
channels:
  - defaults # pylint
  - conda-forge
  - anaconda # graphviz
dependencies:
  - pylint
  - graphviz
  - black
  - isort
  - python-dotenv
  - xeus-python
  - pip
  - pip:
      - doit
